### ISSUE TITLE
Addition some middleware

### ISSUE THREAD

**Issue by tobyapi** [samueleaton/raze#2]
Hi, Sam Eaton.
This is the very stuff I want.

I want to add some [Rack](https://github.com/rack/rack/wiki/List-of-Middleware) inspired middleware for raze. 

Would I put them to src/raze/middleware?

Thank you.

**Comment by samueleaton** [comment]
Yup. I built raze so that it was easier to start adding middlewares. Was there a specific middleware in mind? 

And I'm not sure what you are asking when you say "Would I put them to src/raze/middleware?". Are you asking how to use middleware in Raze?

**Comment by unreadable** [comment]
@samueleaton I think he's reffering to a pull request, but he doesn't know exactly where to put them.
Adding sessions would be nice too. This project looks nice, is it production ready?

**Comment by tobyapi** [comment]
Yes. But I think if you want to keep simple this framework, I will implement another project.

**Comment by samueleaton** [comment]
Exactly. I would like to keep this project simple. Mainly just a router with middleware functionality. Anything else can be a middleware.

I'm going to be adding any decent middlewares to the website in a middlewares page.

@krypton97 We're using it in production but are not doing anything special with it. Its a pretty basic REST API that sits on top of Redis. 

Sessions as part of the web framework, in my opinion, is not the best idea because it isn't scalable. As soon as you start load balancing multiple servers then you have to guarantee that the http calls are sticky. Its better to use a centralized session storage (ie Redis) or store a signed session token on the client (ie JWT). 

But either way, a session middleware wouldn't be too hard to build as a plugin.

**Comment by tobyapi** [comment]
I understood. Thank you!

**Comment by TobiasGSmollett** [comment]
I understood. Thank you!

**Comment by unreadable** [comment]
@samueleaton I agree, keep it as simple as possible, but some basic middlewares like csrf, cors, sessions wouldn't hurt ;)

**Comment by z64** [comment]
I agree, it would be great to supply some "stock" middleware within the library, that isn't `require`'d anywhere. The compiler will ignore it unless the user explicitly `require "raze/middleware/json"`, so we can really put whatever we like in at no compile-time cost to the end user. :+1:

**Comment by unreadable** [comment]
I'll try to submit a pull request with some basic middlewares meanwhile

**Comment by samueleaton** [comment]
Oh yeah now I'm understanding the premise of this issue. I like the idea of putting some middlewares in `src/middleware`. But I don't think all middlewares should be included in `src/middleware`, just a set of core middlewares, right?

I'll clean up the website code and make it a public repo as well. Then we can have a page that list *Raze Middlewares* that are in `src/middleware` and *Community Middlewares* that are available externally.

**Comment by z64** [comment]
Yeah, we should provide for the most common, practical use cases that aren't needed by the minimalist (and thus not required by default) but needed for your average full-stack app. More complicated middleware (especially, outright those that rely on additional shards, like ones that use a DB or cache) should indeed be left to their own shards.

**Comment by unreadable** [comment]
Agreed, core middlewares and community middlewares segmentation seems the best!
