### ISSUE TITLE
Catching JSON from a POST; can't work out how to read context.request.body

### ISSUE THREAD

**Issue by andy-twosticks** [samueleaton/raze#3]
I have a really simple program:

```
require "raze"

post ARGV[1] do |context|
  puts context.request.body.inspect
end

Raze.config.port = ARGV[0].to_i
Raze.run
```

What I want to be able to do is POST JSON to an endpoint in Raze and have it report that JSON to standard out.  

But I can't work out how to read the request body. (In the equivalent program in Ruby and Sinatra, it's just `request.body.read`.)

The above program outputs:

```
#<HTTP::FixedLengthContent:0xe2d960 @encoder=nil, @decoder=nil, @encoding=nil, @sync_close=false, @read_remaining=23, @closed=false, @io=#<TCPSocket:fd 10>>
```

 I've tried a number of things, including this:

```
buffer = Bytes.new(1000)
numbytes = context.request.body.io.read(buffer)
puts buffer[0, numbytes].inspect
```
... which gets me:

```
Error in src/bulldog.cr:12: undefined method 'io' for File::PReader (compile-time type is (IO | Nil))
  numbytes = context.request.body.io.read(buffer)
```
...which seems odd. 

I can't seem to make anything work. All I want to do is read the incoming request body...

**Comment by z64** [comment]
Hi there!

The `request.body` you are looking at is a [standard library `HTTP::Request`](https://crystal-lang.org/api/0.23.1/HTTP/Request.html#body%3AIO%3F-instance-method). `#body` returns the union type `IO | Nil` (aka `IO?`) which means an IO is not guaranteed to be present (it can't predict what your users will send you), and you have to handle this case.

There are a few approaches you can use, but probably the easiest and safest is to use the `if var` semantic outlined by [the docs](https://crystal-lang.org/docs/syntax_and_semantics/if_var.html?q=):
```cr
if body = ctx.request.body
  body #=> IO (guaranteed not to be `nil` inside this branch)
else
  # optionally do something if `body` is `nil`
  ctx.halt_plain "Bad request", 400
end
```
From there, as a suggestion, you can pass that IO to a `JSON.mapping`-mapped class. ([docs here](https://crystal-lang.org/api/0.23.1/JSON.html#mapping%28properties%2Cstrict%3Dfalse%29-macro))
```cr

# Maps to JSON:
# { "bar": "something", "baz": 1234 }
class Foo
  JSON.mapping(bar: String, baz: Int32)
end

# .. in your Raze handler ..

if body = ctx.request.body
  foo = Foo.from_json(body)
  # Do things with `foo`
  foo.bar #=> "something" : String
  foo.baz #=> 1234 : Int32
end
```
Hoped this helped! Be sure to check out the surrounding documentation in the Crystal Docs for other tips on working with union types, and specifically nilable ones. Any further questions I'll do my best to answer :)

---

To also further explain, in your code here:
```cr
post ARGV[1] do |context|
  puts context.request.body.inspect
end
```
You were seeing that output because that was the *runtime* value. Crystal performs static type checking at *compile time* to help ensure runtime safety, which is why trying to do anything to `request.body` without reducing its type to `IO` (instead of `IO?`) will not compile.

**Comment by samueleaton** [comment]
I'm working on a middleware that will parse the request body for `json` and `x-www-form-urlencoded`

for now, you can use `gets_to_end` on the body (`io`) like this:

```ruby
post "/my-route" do |ctx|
  body = ctx.request.body.not_nil!.gets_to_end
  json = JSON.parse(body)
  json["name"].as_s
end
```

```bash
curl -d '{"name":"sam"}' -H "Content-Type: application/json" -X POST http://localhost:7777/my-route
```

Note that I'm not doing any sanity checks to guarantee that the body is not `nil` in that example.

**Comment by andy-twosticks** [comment]
Well, thank you both. I'm learning a lot (including, apparently, that I've forgotten how to work with compiled languages). Those are two excellent answers.  But unfortunately they don't solve my problem.

Try one:

```
require "raze"

post ARGV[1] do |context|
  puts context.request.body.inspect

  if (body = context.request.body)
    puts body.gets_to_end.inspect
  else
    puts "Bad body!"
  end
end

Raze.config.port = ARGV[0].to_i
Raze.run
```
Results in:

```
Index out of bounds (IndexError)
0x4bcb07: *CallStack::unwind:Array(Pointer(Void)) at ??
0x4c9968: at at /opt/crystal/src/indexable.cr 53:17
0x4c98f6: [] at /opt/crystal/src/indexable.cr 74:5
0x49f503: __crystal_main at /home/jonea/andy/bulldog/src/bulldog.cr 3:6
0x4b2479: main at /opt/crystal/src/main.cr 12:15
0x7f3882b91b35: __libc_start_main at ??
0x49ea0d: ??? at ??
0x0: ??? at ??
```

I don't know how to debug that -- it appears not to be happening in my code.  (And more direct copies of the examples that you both gave me all, interestingly, give exactly the same error.)  Try two:

```
require "raze"

post ARGV[1] do |context|
  puts context.request.body.inspect

  if (body = context.request.body)
    buffer = Bytes.new(1000)
    numbytes = body.io.read(buffer)
    puts buffer[0, numbytes].inspect
  else
    puts "Bad body!"
  end
end

Raze.config.port = ARGV[0].to_i
Raze.run
```

Gives me the same error I started with, "undefined method io for File::PReader".  *Now* I understand that this is likely because of type checking at compile time, and not anything to do with the state of my code as a Ruby programmer would see it.  

It very much looks as if at runtime, body has an io object; but at compile time it has something else, a File::PReader object.  If this is true, what is to be done?  I don't control the definition of these objects.

**Comment by z64** [comment]
This exception: 

> Index out of bounds (IndexError)

Is likely happening on one of your ARGV[index] calls.

Here, you seem to be misunderstanding something:

> `numbytes = body.io.read(buffer)`

`body` *is* an IO. You do not get an IO from it ; it is already the object that you want to `gets_to_end` as shown in Sam's example.

**Comment by andy-twosticks** [comment]
@z64 --- Urgh.  I'm so sorry. First thing in the morning here.  

You are of course right.  All the examples you both gave me now work.  Many thanks for all the help.

(Although it's interesting that when I inspect body at runtime, it says that it has an IO object inside it. This is not true? Or it's true but unhelpful.)

**Comment by z64** [comment]
No problem :) Glad you got it working.

And, I'm actually unsure what that class is - `File::PReader`. After a quick search on the API I don't see it as a publicly visible class. 

In any case, regardless of what it is, it should be an object composed with the `IO` mixin (otherwise it would not complie) giving it an IO-like interface described [here](https://crystal-lang.org/api/0.23.1/IO.html)

**Comment by samueleaton** [comment]
@andy-twosticks 
You can use the `?` on hashes to prevent the `Index out of bounds (IndexError)`. The `?` will return `nil` if the value doesn't exist.

So you could do something like this:

```ruby
if port = ARGV[0]?
  Raze.config.port = port.to_i
else
  raise "No port given"
end
```

Now if you don't pass a port as an arg, Crystal will spit this up to the console:

```
No port given (Exception)
0x107ac7655: *CallStack::unwind:Array(Pointer(Void)) at ??
[...etc.]
```

**Comment by samueleaton** [comment]
@z64 Yeah it has a `:nodoc:` in the source. [File::PReader](https://github.com/crystal-lang/crystal/blob/1cca55485db996c8d8f0aeff53c7d0f6286126fa/src/file/preader.cr)

**Comment by z64** [comment]
@samueleaton interesting! Thanks :)
